sudo: required
services:
- docker
language: bash
script:
- docker pull sofwerx/swx-tensorflow-android:latest
- docker build --cache-from sofwerx/swx-tensorflow-android:latest --build-arg TRAVIS_TAG=${TRAVIS_TAG} -t sofwerx/swx-tensorflow-android:latest .
- docker-compose up
after_success:
- mv outputs/sofwerx-android-debug.apk swx-tensorflow-android-debug-${TRAVIS_TAG}.apk
- mv outputs/sofwerx-android-release-unsigned.apk swx-tensorflow-android-release-unsigned-${TRAVIS_TAG}.apk
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push sofwerx/swx-tensorflow-android
branches:
  only:
  - master
  - "/^v\\d.*$/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "${GITHUB_TOKEN}"
  file:
  - swx-tensorflow-android-debug-${TRAVIS_TAG}.apk
  - swx-tensorflow-android-release-unsigned-${TRAVIS_TAG}.apk
  on:
    tags: true
    repo: "${TRAVIS_REPO_SLUG}"
notifications:
  slack:
    rooms:
      secure: ECWCdW13q75kLujQGqW82aHEq7IbQ0Uj+K1jm3Qj/G1gEeQvc4gYOm44ZjuhezdpPFODy28mBYNQvQfnFKiwYGYmKq2gnM5Esg7deHKUVyPFfn+npznhFwPODj/mn2mh5mMfK1K775GXewZJoUZd31KqQXUvDNj2nR9o3xY3CnecResUgllo59hXcoky/eB/j0AbiQMXZ+xjmA9mVA57XAOYnyL2d3tg5k8W96R/BvKRoK1Pd0koH2K1DvCN3f0ai/B17Vg9bWW2EaaxZ5ypuORjmJGLdOQ1RUh4byEcC5xtfWcfS0bTug3EUo2RXo+anKCA0x0+jkfnNjUpEimmmyD1NTHfk0uxhW1vD9FYGOvrd6ZY48EK7u3CD1O4VrlvC5lRoPkh1QPZkEWGMkeUPIjrUEwQ/laq/YaZg2aZbBsV4YiYcyM1I9/dKfYHSiQ/Snmf1kD23XxXH0nmp7YiuV7jkaVXHZKoJInFOL95ODDMpCSvqcAroLauTYhrZ3ZJodzvDnJG5OF2uLcQeY/58e4eAWgW18Ie4Oy2Q8tPPzhFewK0NEl28+ehhH4ja2vB4wINIP2qDHBkMqmDI8CQZUv13zSZPrRYV3LLvEMkN57eDfI/mqo/hkE9ZZFld99Unniwbqn7HCwM1QKnIz9BrzdYPTzMZ4z+mLVXCSXrjlQ=
