version: '2'

services:
  tensorflow:
    container_name: tensorflow
    image: sofwerx/swx-tensorflow-android:lite
    build:
      context: .
      dockerfile: Dockerfile.lite
#      cache_from: sofwerx/swx-tensorflow-android:latest
    volumes:
      - "./outputs:/outputs"

