version: '2'

services:
  tensorflow:
    container_name: tensorflow
    image: sofwerx/swx-tensorflow-android:latest
    build:
      context: .
      dockerfile: Dockerfile
#      cache_from: sofwerx/swx-tensorflow-android:latest
      args:
        - TRAVIS_TAG=${TRAVIS_TAG}
    volumes:
      - "./outputs:/outputs"

